import type { CompletePlanWeatherResolver } from "./complete-plan";
import type { Coordinate } from "../domain/coordinates";
import type { JsonValue, WeatherReferenceSnapshot } from "../domain/route";
import {
  createSampledPhaseWindResolver,
  type LoadedWindsData,
  type WorkerWindsAdapter,
  type WorkerWindsSelectionInput,
} from "../services/weather/winds-adapter";

export interface WorkerWindsPlanWeatherInput {
  /** Explicit user-selected product valid time; it is not inferred from departure. */
  readonly selectedForecastValidTimeUtc: string;
  /** Explicit representative coordinate for the documented nearest-station rule. */
  readonly stationSelectionCoordinate: Coordinate;
  /** Generated by the application use-case layer and persisted atomically with the resulting revision. */
  readonly weatherSnapshotId: string;
}

type WindsLoader = Pick<WorkerWindsAdapter, "load">;

/**
 * Adapts the typed same-origin Worker client into the complete-plan weather
 * contract. It requires caller-provided forecast/station choices because the
 * current draft schema does not persist either choice. It returns, but never
 * writes, immutable evidence so a use case can save it atomically with a plan.
 */
export const createWorkerWindsPlanWeatherResolver = (
  winds: WindsLoader,
  input: WorkerWindsPlanWeatherInput,
): CompletePlanWeatherResolver => ({
  resolve: async ({ draft }) => {
    const loaded = await winds.load(selectionInput(draft.route.points.map((point) => point.coordinate), draft.departureTimeUtc, input));
    const snapshot = weatherSnapshot(input.weatherSnapshotId, loaded);
    return {
      snapshotIds: [snapshot.id],
      referenceSnapshots: [snapshot],
      selectedForecastValidTimeUtc: loaded.forecastSelection.period.id,
      phaseWindResolver: createSampledPhaseWindResolver(loaded),
      warnings: [],
      provenance: weatherProvenance(loaded),
    };
  },
});

const selectionInput = (
  routeCoordinates: readonly Coordinate[],
  departureTimeUtc: string,
  input: WorkerWindsPlanWeatherInput,
): WorkerWindsSelectionInput => ({
  routeCoordinates,
  stationSelectionCoordinate: input.stationSelectionCoordinate,
  selectedForecastValidTimeUtc: input.selectedForecastValidTimeUtc,
  departureTimeUtc,
});

const weatherSnapshot = (id: string, data: LoadedWindsData): WeatherReferenceSnapshot => ({
  schemaVersion: 1,
  id,
  retrievedAt: data.forecastPayload.forecast.fetchedAt,
  source: "aviationweather:NCEP-FB-Winds-Temps",
  payload: {
    schema: "winds-aloft-reference-snapshot/v1",
    selectedStation: {
      id: data.stationSelection.station.id,
      latitude: data.stationSelection.station.coordinate.latitude,
      longitude: data.stationSelection.station.coordinate.longitude,
      distanceNauticalMiles: data.stationSelection.distance,
      selectionMethod: data.stationSelection.selectionMethod,
    },
    selectedForecast: {
      validAt: data.forecastSelection.period.id,
      validFromUtc: data.forecastSelection.period.validFromUtc,
      validToUtc: data.forecastSelection.period.validToUtc,
      issuedAt: data.forecastPayload.forecast.issuedAt,
      rawProduct: data.forecastPayload.forecast.rawProduct,
      levels: data.forecastPayload.forecast.levels.map((level) => ({
        altitudeFeet: level.altitudeFt,
        windFromDegreesTrue: level.windFromDegTrue,
        windSpeedKnots: level.windSpeedKt,
        temperatureCelsius: level.temperatureC,
        availability: level.availability,
        raw: level.raw,
      })),
    },
    requestIds: data.provenance.requestIds,
  },
});

const weatherProvenance = (data: LoadedWindsData): JsonValue => ({
  source: "NCEP FB Winds/Temps (legacy FD)",
  selectedStationId: data.stationSelection.station.id,
  selectedForecastValidTimeUtc: data.forecastSelection.period.id,
  stationDiscoveryRequestId: data.provenance.requestIds.stationDiscovery,
  forecastRequestId: data.provenance.requestIds.forecast,
  forecastCacheStatus: data.provenance.forecast.cache.status,
  forecastFetchedAt: data.provenance.forecast.fetchedAt,
});
