import type { CompletePlanWeatherResolver } from "./complete-plan";
import type { Coordinate } from "../domain/coordinates";
import type { AirportRoutePoint, JsonValue, WeatherReferenceSnapshot } from "../domain/route";
import {
  createSampledPhaseWindResolver,
  type LoadedWindsData,
  type WorkerWindsAdapter,
  type WorkerWindsSelectionInput,
} from "../services/weather/winds-adapter";
import type { MetarTransportClient } from "../services/weather/winds-client";
import { isJsonValue } from "../services/storage/validation";

export interface WorkerWindsPlanWeatherInput {
  /** Explicit representative coordinate for the documented nearest-station rule. */
  readonly stationSelectionCoordinate: Coordinate;
  /** Generated by the application use-case layer and persisted atomically with the resulting revision. */
  readonly weatherSnapshotId: string;
}

type WindsLoader = Pick<WorkerWindsAdapter, "load">;

/**
 * Adapts the typed same-origin Worker client into the complete-plan weather
 * contract. It requires caller-provided forecast/station choices because the
 * current draft schema does not persist either choice. It returns, but never
 * writes, immutable evidence so a use case can save it atomically with a plan.
 */
export const createWorkerWindsPlanWeatherResolver = (
  winds: WindsLoader,
  input: WorkerWindsPlanWeatherInput,
  metarClient?: MetarTransportClient,
): CompletePlanWeatherResolver => ({
  resolve: async ({ draft }) => {
    if (draft.weatherSelection === undefined) throw new Error("Choose an available winds forecast period explicitly before calculating the plan.");
    const departure = draft.route.points[0];
    if (departure?.kind !== "airport") throw new Error("A departure airport with field elevation is required for weather planning.");
    // A METAR anchor improves low-altitude interpolation, but it is optional:
    // winds entirely within the published FB envelope remain calculable when
    // the runway-picker METAR dependency is temporarily unavailable.
    const metarIcao = draft.weatherSelection.surfaceWeatherIcao;
    const metar = metarIcao === undefined || metarClient === undefined ? undefined : await metarClient.fetchMetar(metarIcao).catch(() => undefined);
    const loaded = await winds.load(selectionInput(draft.route.points.map((point) => point.coordinate), draft.departureTimeUtc, draft.weatherSelection.forecastValidTimeUtc, input, departure, metarIcao, metar));
    const snapshot = weatherSnapshot(input.weatherSnapshotId, loaded);
    return {
      snapshotIds: [snapshot.id],
      referenceSnapshots: [snapshot],
      selectedForecastValidTimeUtc: loaded.forecastSelection.period.id,
      phaseWindResolver: createSampledPhaseWindResolver(loaded),
      loadedWindsData: loaded,
      warnings: weatherWarnings(metarIcao, metar, loaded),
      provenance: weatherProvenance(loaded),
    };
  },
});

const weatherWarnings = (
  metarIcao: string | undefined,
  metar: Awaited<ReturnType<MetarTransportClient["fetchMetar"]>> | undefined,
  loaded: LoadedWindsData,
): readonly string[] => [
  ...(metarIcao !== undefined && metar === undefined
    ? [`Selected surface METAR ${metarIcao} could not be loaded; calculation uses winds aloft only.`]
    : []),
  ...(metarIcao !== undefined && metar !== undefined && loaded.surfaceToAloftInterpolation?.status === "unavailable"
    ? [`Selected surface METAR ${metarIcao} was not usable; calculation uses winds aloft only.`]
    : []),
  ...(loaded.provenance.forecast.cache.status === "stale_on_error"
    ? ["Winds forecast was served from stale cache because the upstream refresh failed. Verify current official weather before flight."]
    : []),
];

const selectionInput = (
  routeCoordinates: readonly Coordinate[],
  departureTimeUtc: string,
  selectedForecastValidTimeUtc: string,
  input: WorkerWindsPlanWeatherInput,
  departure: AirportRoutePoint,
  selectedSurfaceWeatherIcao: string | undefined,
  metar?: Awaited<ReturnType<MetarTransportClient["fetchMetar"]>>,
): WorkerWindsSelectionInput => ({
  routeCoordinates,
  stationSelectionCoordinate: input.stationSelectionCoordinate,
  selectedForecastValidTimeUtc,
  departureTimeUtc,
  ...(metar === undefined ? {} : { departureSurfaceWind: { airportIcao: departure.icao, surfaceWeatherIcao: selectedSurfaceWeatherIcao, fieldElevationFeetMsl: departure.elevationFeetMsl, metar } }),
});

const weatherSnapshot = (id: string, data: LoadedWindsData): WeatherReferenceSnapshot => ({
  schemaVersion: 1,
  id,
  retrievedAt: data.forecastPayload.forecast.fetchedAt,
  source: "aviationweather:NCEP-FB-Winds-Temps",
  payload: {
    schema: "winds-aloft-reference-snapshot/v1",
    selectedStation: {
      id: data.stationSelection.station.id,
      latitude: data.stationSelection.station.coordinate.latitude,
      longitude: data.stationSelection.station.coordinate.longitude,
      distanceNauticalMiles: data.stationSelection.distance,
      selectionMethod: data.stationSelection.selectionMethod,
    },
    selectedForecast: {
      validAt: data.forecastSelection.period.id,
      validFromUtc: data.forecastSelection.period.validFromUtc,
      validToUtc: data.forecastSelection.period.validToUtc,
      issuedAt: data.forecastPayload.forecast.issuedAt,
      rawProduct: data.forecastPayload.forecast.rawProduct,
      levels: data.forecastPayload.forecast.levels.map((level) => ({
        altitudeFeet: level.altitudeFt,
        windFromDegreesTrue: level.windFromDegTrue,
        windSpeedKnots: level.windSpeedKt,
        temperatureCelsius: level.temperatureC,
        availability: level.availability,
        raw: level.raw,
      })),
    },
    surfaceToAloftInterpolation: jsonEvidence(data.surfaceToAloftInterpolation),
    requestIds: data.provenance.requestIds,
  },
});

const jsonEvidence = (value: unknown): JsonValue => {
  if (value === undefined) return null;
  const serialized: unknown = JSON.parse(JSON.stringify(value));
  if (!isJsonValue(serialized)) throw new Error("Weather evidence could not be stored as bounded JSON.");
  return serialized;
};

const weatherProvenance = (data: LoadedWindsData): JsonValue => ({
  source: "NCEP FB Winds/Temps (legacy FD)",
  selectedStationId: data.stationSelection.station.id,
  selectedForecastValidTimeUtc: data.forecastSelection.period.id,
  stationDiscoveryRequestId: data.provenance.requestIds.stationDiscovery,
  forecastRequestId: data.provenance.requestIds.forecast,
  forecastCacheStatus: data.provenance.forecast.cache.status,
  forecastFetchedAt: data.provenance.forecast.fetchedAt,
});
